Add documentation for Eclipse plugin
42Crunch/eclipse-openapi pull request #10
Opened 2022-08-04 13:19 UTC by ak1394

Add documentation for Eclipse plugin

2022-08-04 13:24 UTC, isamauny commented on openapi-plugin/docs/README.md
> +This extension features optional integration with [42Crunch Platform](https://platform.42crunch.com/). To enable it please configure your credentials in the settings wizard.
Reference the docs page which explain how to create the relevant token, with proper scopes.

2022-08-04 13:24 UTC, isamauny commented on openapi-plugin/docs/README.md
> +- No schema validation
What does that mean ? Validation of what ?

2022-08-04 13:27 UTC, isamauny commented on openapi-plugin/docs/README.md
> +- Platform token is stored encrypted, but can be decrypted using brute force, it is up to a user to keep all workspace data safe and secure.
Might want to phrase this differently -  Isn't the token stored locally ? This assumes someone would do brute force on the developer laptop, which is very unlikely. I would move this to a recommendation section and not to a known issue list. This is really a recommendation, not a problem we will fix.

2022-08-04 13:30 UTC, isamauny commented on openapi-plugin/docs/README.md
> +Then you can work with the platform using the tree view
Obviously, this is very poor, we need a whole section to explain how to navigate the menu, create collections, import APIs, view imported reports, etc. 

May be I can write that section separately and we can use from all IDEs ? The functionality is pretty much the same isn't it ?

2022-08-04 13:30 UTC, isamauny requested changes
We need to fill up the 42Crunch Platform section and update the known issues one.

2022-08-08 10:47 UTC, vfateev commented on openapi-plugin/docs/README.md
> +This extension features optional integration with [42Crunch Platform](https://platform.42crunch.com/). To enable it please configure your credentials in the settings wizard.
Done

2022-08-08 10:48 UTC, vfateev commented on openapi-plugin/docs/README.md
> +- No schema validation
Validation of OpenAPI files

2022-08-08 10:50 UTC, vfateev commented on openapi-plugin/docs/README.md
> +- Platform token is stored encrypted, but can be decrypted using brute force, it is up to a user to keep all workspace data safe and secure.
Yes, it is stored locally. Agree, moved it as a note to Integration with 42Crunch Platform section.

2022-08-08 10:52 UTC, vfateev commented on openapi-plugin/docs/README.md
> +Then you can work with the platform using the tree view
Yes, platform functionality is the same across all our plugins.
Having one single section and referencing it would be the best choice.

2022-08-10 14:08 UTC, merged